run_analysis <- function() {
  
  ## Let's get the messy dataset ready first ...
  
  ## Let's start with the test data ...
  
  subjectcol_test <- read.table("./test/subject_test.txt", header = FALSE)  # First load the subject column of test data set ...
  activitycol_test <- read.table("./test/y_test.txt", header = FALSE)  # Next load the activity column of test data set ...
  dataset_test <- read.table("./test/X_test.txt", header = FALSE)  # Then load the other columns of test data set ...
  full_dataset_test <- cbind(subjectcol_test,activitycol_test, dataset_test) # At the end, bind the datasets column-wise to get the full test dataset ...

  ## Now, let's load the training data ...
  subjectcol_train <- read.table("./train/subject_train.txt", header = FALSE) # First load the subject column of training data set ...
  activitycol_train <- read.table("./train/y_train.txt", header = FALSE) # Next load the activity column of training data set ...
  dataset_train <- read.table("./train/X_train.txt", header = FALSE) # Then load the other columns of training data set ...
  full_dataset_train <- cbind(subjectcol_train,activitycol_train, dataset_train) # At the end, bind the datasets column-wise to get the full training dataset ...

  ## Bind the test and training datasets to get the full data set ...
  full_data <- rbind(full_dataset_test, full_dataset_train)  # Bind the test and training data sets together by rows to get the full data set ...

  ## Get the features list loaded in a data frame and get it subsetted...
  features <- read.table("./features.txt", header = FALSE)
  library(dplyr)
  feature_names <- select(features, V2)

  ## Now append "Subjects" and "Activity" to the list of features
  feature_append <- data.frame(c("Subjects", "Activity"))
  names(feature_append) <- c("V2")
  feature_final <- rbind(feature_append,feature_names)
  
  ## Now let's get feature names added to full_data as column header ..
  colnames <- feature_final[ ,1]
  names(full_data) <- colnames
  
  ## Cool buddy, Mr. Messy Data is ready for the show. Let's get him cleaned now ...

  grouped_data <- group_by(full_data, Subjects, Activity) # First get the data grouped by Subjects and Activity ...
  tmp <- grouped_data[,c("Subjects","Activity",grep("mean()", names(grouped_data), value=TRUE),grep("std", names(grouped_data), value=TRUE))]
  group_by(tmp, Subjects, Activity)
  tidy_data <- tmp %>% summarise_each(funs(mean))

  ## Finally, let's get Activity Numbers replaced by Activity Names ...
  activity_label <- read.table("./activity_labels.txt", header = FALSE) # Load the activity labels table ....
  names(activity_label) <- c("Activity", "Activity_Name")
  temp <- merge(activity_label, tidy_data, by = "Activity", all = TRUE)
  final_tidy_data <- select(temp, -Activity)  ## Removing column "Activity"
  arranged_tidy_data <- arrange(final_tidy_data, Subjects)
  
  write.table(arranged_tidy_data, file = "./tidy_data.txt", sep = ",", row.names = FALSE, col.names = TRUE)
}